"""add writing modles

Revision ID: 248b93e14027
Revises: 623cfb220757
Create Date: 2026-04-12 12:24:36.659306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248b93e14027'
down_revision: Union[str, Sequence[str], None] = '623cfb220757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writing_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('test_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writing_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=True),
    sa.Column('task_number', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('task1_academic', 'task1_general', 'task2', name='writingtasktype'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('stimulus', sa.Text(), nullable=True),
    sa.Column('min_words', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['writing_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ielts_tests', sa.Column('writing_test_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'ielts_tests', 'writing_tests', ['writing_test_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ielts_tests', type_='foreignkey')
    op.drop_column('ielts_tests', 'writing_test_id')
    op.drop_table('writing_tasks')
    op.drop_table('writing_tests')
    # ### end Alembic commands ###
