"""add speaking models

Revision ID: 2da0ca52f78a
Revises: 248b93e14027
Create Date: 2026-04-12 16:15:43.702757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da0ca52f78a'
down_revision: Union[str, Sequence[str], None] = '248b93e14027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaking_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speaking_parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=True),
    sa.Column('part_number', sa.Integer(), nullable=False),
    sa.Column('part_type', sa.Enum('part1', 'part2', 'part3', name='speakingparttype'), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('cue_card', sa.Text(), nullable=True),
    sa.Column('prep_time_seconds', sa.Integer(), nullable=True),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['speaking_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ielts_tests', sa.Column('speaking_test_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'ielts_tests', 'speaking_tests', ['speaking_test_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ielts_tests', type_='foreignkey')
    op.drop_column('ielts_tests', 'speaking_test_id')
    op.drop_table('speaking_parts')
    op.drop_table('speaking_tests')
    # ### end Alembic commands ###
