"""add reading models

Revision ID: 623cfb220757
Revises: 5fde051f9613
Create Date: 2026-04-11 23:11:11.844516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623cfb220757'
down_revision: Union[str, Sequence[str], None] = '5fde051f9613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('test_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_passages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=True),
    sa.Column('passage_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('paragraphs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['reading_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_question_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('passage_id', sa.UUID(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('mcq', 'tfng', 'fill', 'matching_headings', 'matching_info', 'short_answer', name='readingquestiontype'), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('heading_options', sa.JSON(), nullable=True),
    sa.Column('paragraph_labels', sa.JSON(), nullable=True),
    sa.Column('word_limit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['passage_id'], ['reading_passages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('answer_key', sa.JSON(), nullable=False),
    sa.Column('wrong_answer_tip', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['reading_question_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ielts_tests', sa.Column('reading_test_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'ielts_tests', 'reading_tests', ['reading_test_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ielts_tests', type_='foreignkey')
    op.drop_column('ielts_tests', 'reading_test_id')
    op.drop_table('reading_questions')
    op.drop_table('reading_question_groups')
    op.drop_table('reading_passages')
    op.drop_table('reading_tests')
    # ### end Alembic commands ###
