"""changes to the user and subscription model

Revision ID: b3cd5c984904
Revises: 2da0ca52f78a
Create Date: 2026-04-12 22:36:20.437072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cd5c984904'
down_revision: Union[str, Sequence[str], None] = '2da0ca52f78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_sessions', sa.Column('module_started_at', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('lemonsqueezy_customer_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['lemonsqueezy_customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'lemonsqueezy_customer_id')
    op.drop_column('users', 'is_admin')
    op.drop_column('test_sessions', 'module_started_at')
    # ### end Alembic commands ###
